version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:942188694929:task-definition/helloworldtask:1"
        LoadBalancerInfo:
          ContainerName: "helloworldapicontainer"
          ContainerPort: "80"
        PlatformVersion: "LATEST"